url: "https://coderic.net" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "Coderic" # the name of your site, e.g. ACME Corp.
remote_theme: Coderic/jekyll-theme-coderic
include: ['.well-known']
plugins:
  - jekyll-remote-theme